DROP TABLE IF EXISTS books CASCADE;
DROP TABLE IF EXISTS autors CASCADE;
DROP TABLE IF EXISTS books_autors CASCADE;

CREATE TABLE IF NOT EXISTS books
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    title       CHARACTER VARYING(255)        NOT NULL,
    ISBN        CHARACTER VARYING(255) UNIQUE NOT NULL,
    CONSTRAINT pk_books PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS autors
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name CHARACTER VARYING(255) NOT NULL,
    CONSTRAINT pk_autors PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS books_autors
(
    books_id  BIGINT NOT NULL,
    autors_id BIGINT NOT NULL,
    CONSTRAINT pk_books_autors PRIMARY KEY (books_id, autors_id),
    CONSTRAINT fk_books_autors_books_id FOREIGN KEY (books_id) REFERENCES books (id),
    CONSTRAINT fk_books_autors_autors_id FOREIGN KEY (autors_id) REFERENCES autors (id)
);
